name: CloudFormation nag
on: [push]

#on: # si no queremos q se ejecute cada vez q se hagan todos los push, sino los de main
#  pull_request_target:
#    branches:
#      -main

jobs: 
  cloudformation-nag: #podemos definir nnuestros propios nombres para los jobs (es un mapa, le podemos agregar más cosas)
    runs-on: ubuntu-latest #hay maquinas de linux, windows, x64, etc. 
    steps: #lista de pasos q se van a ejecutar dentro de nuestra maquinita. Recordar que cada "run"" se va aejcutar en una sesion diferente
      - uses: actions/checkout@v4
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install ruby brew-gem
          brew gem install cfn-nag
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cfn_nag_scan --input-path ec2-sg-template.yaml

      
